name: timo_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  google_maps_flutter: ^2.2.5
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  syncfusion_flutter_calendar: ^18.4.46
  google_sign_in: ^5.4.2
  googleapis: ^9.2.0
  firebase_core: ^2.7.1
  firebase_database: ^10.0.15
  flutter_ringtone_player: ^3.2.0
  shared_preferences: any
  path_provider: any

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

