name: timo_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  google_maps_flutter: ^2.2.5
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  #syncfusion_flutter_calendar: ^18.4.46
  syncfusion_flutter_calendar: ^21.1.41
  google_sign_in: ^5.4.2
  googleapis: ^9.2.0
  firebase_core: ^2.7.1
  firebase_database: ^10.0.15
  flutter_ringtone_player: ^3.2.0
  path_provider: any
  google_fonts: ^4.0.3
  intl: ^0.17.0
  googleapis_auth: ^1.4.0
  url_launcher: ^6.1.10
  firebase_auth: ^4.2.2

  smooth_page_indicator: ^1.0.1

  currency_icons: ^0.3.0
  geolocator: ^9.0.2
  geocoding: ^2.0.0
  flutter_polyline_points: ^1.0.0
  dio: ^5.1.1
  shared_preferences: ^2.1.0
  #flutter_local_notifications: ^13.0.0
  awesome_notifications: ^0.0.6+11
  flutter_background: ^1.0.7
  location: ^4.4.0
  flutter_map: ^3.1.0

#dependency_overrides: 
#  syncfusion_flutter_calendar: ^18.4.46
#  timezone: ^0.9.0
#  flutter_local_notifications: ^13.0.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets: 
    - assets/
